name: responsive_material_app
description: A production-ready Flutter app demonstrating responsive UI with Material Design
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Data
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Image Handling
  image_picker: ^1.0.4

  # UI Utilities
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
